title: Developer's Website
author: GitHub User                                         
description: > # this means to ignore newlines until "baseurl:"
  Posts about random code things

# social links

github_username:  WindChaim # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
